FROM node:carbon-alpine

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm install

COPY . .

RUN npm run prestart:prod
RUN npm ci --only=production

EXPOSE 3000
CMD [ "node", "dist/main.js" ]
