---
name: tests

on:
  pull_request:
    branches:
      - master
      - develop
      - "release/*"
      - "hotfix/*"
      - "feature/*"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
          registry-url: https://nexus.greatminds.dev/repository/npm/

      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-14-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-14

      - name: npm install
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - run: git fetch --all

      - name: lint
        run: npm run lint

      - name: build
        run: npm run build

      - name: test
        run: npm run test:ci:cov

      - name: publish test reports
        run: .github/publish-reports.sh
        if: always()
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          BRANCH: ${{ github.head_ref }}
      - name: Codacy Coverage Reporter
        uses: codacy/codacy-coverage-reporter-action@master
        if: always()
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: ./coverage/lcov.info
